server:
  port: 8101

spring:
  application:
    name: dubbo-order-example
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


#====================================Dubbo config===============================================
dubbo:
  application:
    id: dubbo-order-example
    name: dubbo-order-example
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
    id: dubbo-order-example-registry

#===================================registry config==========================================
management:
  endpoints:
    web:
      exposure:
        include: '*'

#=====================================mybatis\u914D\u7F6E======================================
mybatis:
  mapper-locations: classpath*:/mapper/*.xml


logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error

